# Site settings
title: Rajat Modi
email: 
description: ""
baseurl: ""
url: "http://rajatmodi62.github.io"
# twitter_username: karpathy
github_username:  rajatmodi62
twitter_username: rajatmodi62 # Keep this one
linkedin_username: rajat-modi-54377877 # Find this in your LinkedIn URL
google_scholar_link: https://scholar.google.com/citations?user=Ypzln1UAAAAJ&hl=en # Paste the full URL here
# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
